apiVersion: v1
kind: Service
metadata:
    name: "testkuber001-ad44"
    labels:
        app: "testkuber001-ad44"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testkuber001-ad44"