--- 
apiVersion: v1
kind: Pod
metadata:
  name: example-frontpod-deployment
  labels: 
    app: sample-front
spec: 
  containers: 
    - name: frontend-layer
      image: "gcr.io/macro-mender-279016/samples_frontend_webapp:1.0"
      ports: 
        - containerPort: 80
        - containerPort: 443

