FROM alpine:latest
ARG k8_version=1.23.4
ARG helm_version=3.8.0
ARG os_version=linux
ARG arch=amd64

RUN apk -U upgrade
RUN apk add --no-cache ca-certificates bash git openssh curl gettext jq bind-tools \
    && wget -q https://storage.googleapis.com/kubernetes-release/release/v${k8_version}/bin/${os_version}/${arch}/kubectl -O /usr/local/bin/kubectl \
    && wget -q https://get.helm.sh/helm-v${helm_version}-${os_version}-${arch}.tar.gz -O - | tar -xzO ${os_version}-${arch}/helm > /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm /usr/local/bin/kubectl \
    && mkdir /config \
    && chmod g+rwx /config /root \
    && helm repo add "stable" "https://charts.helm.sh/stable" --force-update \
    && kubectl version --client \
    && helm version

WORKDIR /config

CMD bash
