name: GitHub CR Build and Push Windows

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Disabling for now...

on:
  push:
    branches: [ windows ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ windows ]

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  # github.repository as <account>/<repo>
  
jobs:
  buildPush:
    runs-on: windows-latest
    permissions:
        contents: read
        packages: write
        # This is used to complete the identity challenge
        # with sigstore/fulcio when running outside of PRs.
        id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@39a1a82492fd1ad19af19d61b5f748e4cb6cd1af

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f75d088332b07a08afadf6ac53c74509b9453f12
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Windows Docker metadata
        id: meta
        uses: docker/metadata-action@314ddf6d4a82333bf1bc7630399df41bf68eba09
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/windows

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push Windows Docker image
        id: build-and-push
        uses: docker/build-push-action@175d02bffea74695e96b351069ac938b338802f9
        with:
          context: samples/adhoc-examples/
          file: samples/adhoc-examples/DockerWindows.docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Windows image to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: samples/adhoc-examples/
          file: samples/kubernetes/DockerWindows.docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USER }}/windows



