name: GitHub CR Build and Push

on:
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

  schedule:
    - cron: '0 0 1 * *'

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  # github.repository as <account>/<repo>
  
jobs:
  buildPush:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        # This is used to complete the identity challenge
        # with sigstore/fulcio when running outside of PRs.
        id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@39a1a82492fd1ad19af19d61b5f748e4cb6cd1af

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@5d8785b43a795ee002a17dbf1a2235dc1997224b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Kubectl Docker metadata
        id: meta
        uses: docker/metadata-action@314ddf6d4a82333bf1bc7630399df41bf68eba09
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/alpinekube

      - name: Build and Push Kubectl Docker image
        id: build-and-push
        uses: docker/build-push-action@175d02bffea74695e96b351069ac938b338802f9
        with:
          context: samples/kubernetes/
          file: samples/kubernetes/DockerKubeHelmAlpine.docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract PgClient Docker metadata
        id: meta1
        uses: docker/metadata-action@314ddf6d4a82333bf1bc7630399df41bf68eba09
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/alpine-pgclient

      - name: Build and Push PgClient Docker image
        id: build-and-push1
        uses: docker/build-push-action@175d02bffea74695e96b351069ac938b338802f9
        with:
          context: samples/adhoc-examples/
          file: samples/adhoc-examples/DockerPgClient.docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}

      - name: Extract AWS Docker metadata
        id: metaaws
        uses: docker/metadata-action@314ddf6d4a82333bf1bc7630399df41bf68eba09
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/aws-cli-cdk

      - name: Build and Push AWS Docker image
        id: build-and-push2
        uses: docker/build-push-action@175d02bffea74695e96b351069ac938b338802f9
        with:
          context: samples/aws/
          file: samples/aws/aws-cli-cdk.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metaaws.outputs.tags }}
          labels: ${{ steps.metaaws.outputs.labels }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Kube image to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: samples/kubernetes/
          file: samples/kubernetes/DockerKubeHelmAlpine.docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USER }}/alpinekube

      - name: Build and push email image Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: samples/use-cases/postfix-email-relay/
          file: samples/use-cases/postfix-email-relay/emailServer.docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USER }}/postfixmailrelay

      - name: Build and push Pgclient image to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: samples/adhoc-examples/
          file: samples/adhoc-examples/DockerPgClient.docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USER }}/alpine-pgclient

      - name: Build and push AWS image to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: samples/aws/
          file: samples/aws/aws-cli-cdk.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USER }}/aws-cli-cdk
