apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
        - name: appname
          image: <ECRrepoName>
          ports:
            - containerPort: 8080